### ISSUE TITLE
Fix DockerHub Login Issue

### ISSUE THREAD

**Issue by jgesell** [utsw-bicf/auto-docker#24]
DockerHub is not able to pull non-public images due to only logging in if a new image is created.  Need to ensure it is logging in properly.

**Comment by vsmalladi** [comment]
not fixed re-opening

**Comment by jgesell** [comment]
So, to fix this, we will be bypassing the GitHub Actions login feature, and logging in using Python only.  This will alter the way the CI is currently running significantly, however to the end-user, it should still function the same.
