### ISSUE TITLE
relations.yml errors

### ISSUE THREAD

**Issue by GHAStVHenry** [utsw-bicf/auto-docker#28]
v1.1.0

1. indentation for children:
![image](https://user-images.githubusercontent.com/38675268/110399045-b484e980-803a-11eb-9afb-89c8062d1257.png)

2. null remains in children even after children are added later:
![image](https://user-images.githubusercontent.com/38675268/110399080-c5cdf600-803a-11eb-90b5-244e8042bd63.png)

**Comment by vsmalladi** [comment]
Fix in generating yaml file.  Scrub these bugs going forward in the read and write.

**Comment by jgesell** [comment]
I am adding a flatten functionality to the generation of the parent and child lists, should take care of part of this.  Going to test it on the relations.yaml file that is in GUDMAP.  The logic for removingg null is there, but it is not designed to find null in a sub-list.
